run:
  dir: data/models/${exp_type}/${exp_name}

sweep:
  dir: data/models/${exp_type}
  subdir: ${exp_name}

output_subdir: hydra

job:
  config:
    override_dirname:
      exclude_keys:
        - exp_name