surrogate_onestep:
  _target_: diffusion_nextsim.callbacks.SurrogateOneStepCallback
  variables: ${data.state_variables}
  std: [0.7506, 0.1848, 0.1968, 0.0836, 0.0878]
  n_input_steps: ${data.n_input_steps}
  every_n_step: 250
