_target_: diffusion_nextsim.decoder.StochasticDecoder
stochastic: true
sampling_func:
  _target_: diffusion_nextsim.decoder.FFTSampler
  periodic_spectrum: null
  shift: null
  cov: null
  normalize: true
# SIT SIC damage SIU SIV
mean: [-0.0000, 0.0000, 0.0000, -0.0000, 0.0000]
std: [0.1163, 0.0313, 0.0525, 0.0541, 0.0546]
lower_bound: [0., 0., 0., -.inf, -.inf]
upper_bound: [.inf, 1., 1., .inf, .inf]
